[package]
name = "hello_server"
version = "0.1.0"
authors = ["Ziyan \"Jerry\" Chen <jerryc443@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "^0.3"
async-std = { version = "^1", features = ["unstable", "attributes"] }

[profile.release]
lto = true
panic = 'abort'