name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    # - name: Update Rust
      # run: rustup default nightly && rustup update
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
